blank_issues_enabled: false
contact_links:
    - name: Discussions
      url: https://github.com/StarArmyDev/starmusic/discussions
      about: Considera colocar nuevas ideas en la sección de discusiones
